[package]
name = "util-cursor"
version = "0.1.0"
edition = "2021"

description = "A simple cursor implementation for reading data from array slice."
authors = ["Nur <nurmohammed840@gmail.com>"]
repository = "https://github.com/nurmohammed840/util-cursor.rs"
license = "MIT"

[dependencies]
